server:
  port: 8086
base-url:
  context: /best-deal/cloud-api/v1

log:
  identifierKey: UUID

spring:
  cloud:
    gcp:
      core:
        enabled: true
    function:
      scan:
        packages: com.uom.msc.cse.sdoncloud.detection.application.function

info:
  data:
    temp-img:
      location: "/Users/pasindu/Documents/Msc/Sem 1/Software Development on Cloud Platforms/Project/temp-images"


